version: '3'
services:
  mysql:
    image: "mysql:8.0"
    volumes:
      - "/data/mysql:/var/lib/mysql"

  web:
    image: "surfsoftconsulting/java-web-services-mysql:development"
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.username=mysqluser
      - spring.datasource.password=mysqlpass
      - spring.datasource.url=jdbc:mysql://mysql:3306/mydb?createDatabaseIfNotExist=true
